basic.forever(function () {
    basic.showString("D")
    basic.pause(500)
    basic.showString("L")
    basic.pause(500)
    basic.showString("7")
    basic.pause(500)
    basic.showString("H")
    basic.pause(500)
    basic.showString("F")
    basic.pause(2000)
})
